# Generated by Django 5.2.1 on 2025-05-28 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('attraction_image', models.ImageField(upload_to='attractions/', verbose_name='Изображение достопримечательности')),
                ('days', models.PositiveIntegerField(verbose_name='Количество дней')),
                ('trip_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поездки')),
                ('hotel_class', models.CharField(choices=[('1', '1 звезда'), ('2', '2 звезды'), ('3', '3 звезды'), ('4', '4 звезды'), ('5', '5 звезд')], max_length=1, verbose_name='Класс отеля')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
                'ordering': ['-trip_date'],
            },
        ),
    ]
